apiVersion: v1
kind: Secret
metadata:
  name: k8s-config-rw
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'git@github.com:GITHUB_USERNAME/bux-k8s-config.git'
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDEfgdd2cuXZ3j1iDHTxAFr4bduVt7V3B7oZEX9Ir1fGgAAAJjhtFkZ4bRZ
    GQAAAAtzc2gtZWQyNTUxOQAAACDEfgdd2cuXZ3j1iDHTxAFr4bduVt7V3B7oZEX9Ir1fGg
    AAAEBwsdc8/jkABetMcbqCedL0SqQwOSHWPbYhLAJTizoJksR+B13Zy5dnePWIMdPEAWvh
    t25W3tXcHuhkRf0ivV8aAAAADnJvb3RAbG9jYWxob3N0AQIDBAUGBw==
    -----END OPENSSH PRIVATE KEY-----
